config/routes.rb
Rails.application.routes.draw do
  root "tweet_streams#new"
  resources :tweet_streams, :only => [:new, :create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweet_streams_controller.rb
class TweetStreamsController < ApplicationController
  attr_accessor :twitter_client
  def new
  end

  def create
    @user_name = params[:twitter_handle]
    @tweets = twitter_client.user_timeline(@user_name)
    @follower_count = twitter_client.user(@user_name).followers_count
  end

  def twitter_client
    @twitter_client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = "QmnF0N1nALWJCshk5ecUWXG2n"
      config.consumer_secret     = "N7PoX41YI7YHinZw5qI9XmOskX0nzw60GPtMuQGb7UY6oNh853"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweet_streams/create.html.erb
<h3>Here's some recents tweets for <%= @user_name %>:</h3>
<h5>(<%= @user_name %> has <%= @follower_count %> followers)</h5>
<div>
  <ul>
    <% @tweets.each do |tweet| %>
      <li class="tweet">
      <p>
      <em>
        <%= tweet.user.screen_name %>
      </em>
        says: <%= tweet.text %>
      </p>
      </li>
    <% end %>
  </ul>
</div>

<p>
  <%= link_to("try another user", new_tweet_stream_path) %>
</p>

app/views/tweet_streams/new.html.erb
<h3>Enter a user's twitter handle to view their tweets</h3>
<%= form_tag(tweet_streams_path) do %>
  <%= label_tag "twitter handle" %>
  <%= text_field_tag("twitter_handle")  %>
  <%= submit_tag "dem tweets doe" %>
<% end %>